In [1]:
from fastai.vision import *
from utils import *

When "pretrainedmodels" is not installed: 

In [1]:
from fastai.vision.models.cadene_models import inceptionv4

Error: you must install library "pretrainedmodels" to use the model. Try:
> pip install pretrainedmodels 



AttributeError: module 'pretrainedmodels' has no attribute 'inceptionv4'

In [2]:
inceptionv4

NameError: name 'inceptionv4' is not defined

In [4]:
from fastai.vision.models.cadene_models import inceptionv4

In [5]:
arch_summary(inceptionv4)

(0) BasicConv2d : 3   layers (total: 3)
(1) BasicConv2d : 3   layers (total: 6)
(2) BasicConv2d : 3   layers (total: 9)
(3) Mixed_3a    : 4   layers (total: 13)
(4) Mixed_4a    : 18  layers (total: 31)
(5) Mixed_5a    : 4   layers (total: 35)
(6) Inception_A : 22  layers (total: 57)
(7) Inception_A : 22  layers (total: 79)
(8) Inception_A : 22  layers (total: 101)
(9) Inception_A : 22  layers (total: 123)
(10) Reduction_A : 13  layers (total: 136)
(11) Inception_B : 31  layers (total: 167)
(12) Inception_B : 31  layers (total: 198)
(13) Inception_B : 31  layers (total: 229)
(14) Inception_B : 31  layers (total: 260)
(15) Inception_B : 31  layers (total: 291)
(16) Inception_B : 31  layers (total: 322)
(17) Inception_B : 31  layers (total: 353)
(18) Reduction_B : 19  layers (total: 372)
(19) Inception_C : 31  layers (total: 403)
(20) Inception_C : 31  layers (total: 434)
(21) Inception_C : 31  layers (total: 465)
(22) AvgPool2d   : 1   layers (total: 466)
(23) Linear      : 1   layers (t

In [8]:
learn = create_cnn(FakeData(), inceptionv4, pretrained=True)

In [9]:
get_groups(nn.Sequential(*learn.model[0], *learn.model[1]), learn.layer_groups)

Group 1: ['BasicConv2d', 'BasicConv2d', 'BasicConv2d', 'Mixed_3a', 'Mixed_4a', 'Mixed_5a', 'Inception_A', 'Inception_A', 'Inception_A', 'Inception_A', 'Reduction_A']
Group 2: ['Inception_B', 'Inception_B', 'Inception_B', 'Inception_B', 'Inception_B', 'Inception_B', 'Inception_B', 'Reduction_B', 'Inception_C', 'Inception_C', 'Inception_C']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [10]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[ 0.1859, -0.1454]])


In [11]:
inceptionresnetv2

NameError: name 'inceptionresnetv2' is not defined

In [12]:
from fastai.vision.models.cadene_models import inceptionresnetv2

In [13]:
arch_summary(inceptionresnetv2)

(0) BasicConv2d : 3   layers (total: 3)
(1) BasicConv2d : 3   layers (total: 6)
(2) BasicConv2d : 3   layers (total: 9)
(3) MaxPool2d   : 1   layers (total: 10)
(4) BasicConv2d : 3   layers (total: 13)
(5) BasicConv2d : 3   layers (total: 16)
(6) MaxPool2d   : 1   layers (total: 17)
(7) Mixed_5b    : 22  layers (total: 39)
(8) Sequential  : 200 layers (total: 239)
(9) Mixed_6a    : 13  layers (total: 252)
(10) Sequential  : 280 layers (total: 532)
(11) Mixed_7a    : 22  layers (total: 554)
(12) Sequential  : 126 layers (total: 680)
(13) Block8      : 13  layers (total: 693)
(14) BasicConv2d : 3   layers (total: 696)
(15) AvgPool2d   : 1   layers (total: 697)
(16) Linear      : 1   layers (total: 698)


In [14]:
learn = create_cnn(FakeData(), inceptionresnetv2, pretrained=True)

In [15]:
get_groups(nn.Sequential(*learn.model[0], *learn.model[1]), learn.layer_groups)

Group 1: ['BasicConv2d', 'BasicConv2d', 'BasicConv2d', 'MaxPool2d', 'BasicConv2d', 'BasicConv2d', 'MaxPool2d', 'Mixed_5b', 'Sequential']
Group 2: ['Mixed_6a', 'Sequential', 'Mixed_7a', 'Sequential', 'Block8', 'BasicConv2d']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [16]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[-0.1458,  0.0967]])


In [17]:
nasnetamobile

NameError: name 'nasnetamobile' is not defined

In [18]:
from fastai.vision.models.cadene_models import nasnetamobile

In [19]:
arch_summary(nasnetamobile)

(0) NASNetAMobile: 821 layers (total: 821)


In [20]:
learn = create_cnn(FakeData(), nasnetamobile, pretrained=True)

In [21]:
get_groups(nn.Sequential(*learn.model[0][0].children(), *learn.model[1]), learn.layer_groups)

Group 1: ['Sequential', 'CellStem0', 'CellStem1', 'FirstCell', 'NormalCell', 'NormalCell', 'NormalCell', 'ReductionCell0']
Group 2: ['FirstCell', 'NormalCell', 'NormalCell', 'NormalCell', 'ReductionCell1', 'FirstCell', 'NormalCell', 'NormalCell', 'NormalCell', 'ReLU', 'AvgPool2d', 'Dropout', 'Linear']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [22]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[ 0.6252, -1.9816]])


In [3]:
dpn92

NameError: name 'dpn92' is not defined

In [4]:
from fastai.vision.models.cadene_models import dpn92

In [5]:
arch_summary(dpn92)

(0) Sequential  : 288 layers (total: 288)
(1) Conv2d      : 1   layers (total: 289)


In [6]:
learn = create_cnn(FakeData(), dpn92, pretrained=True)

In [7]:
get_groups(nn.Sequential(*learn.model[0][0], *learn.model[1]), learn.layer_groups)

Group 1: ['InputBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock']
Group 2: ['DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'DualPathBlock', 'CatBnAct']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [8]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[-0.2164,  0.4982]])


In [9]:
xception_cadene

NameError: name 'xception_cadene' is not defined

In [10]:
from fastai.vision.models.cadene_models import xception_cadene

In [11]:
arch_summary(xception_cadene)

(0) Conv2d      : 1   layers (total: 1)
(1) BatchNorm2d : 1   layers (total: 2)
(2) ReLU        : 1   layers (total: 3)
(3) Conv2d      : 1   layers (total: 4)
(4) BatchNorm2d : 1   layers (total: 5)
(5) Block       : 11  layers (total: 16)
(6) Block       : 12  layers (total: 28)
(7) Block       : 12  layers (total: 40)
(8) Block       : 12  layers (total: 52)
(9) Block       : 12  layers (total: 64)
(10) Block       : 12  layers (total: 76)
(11) Block       : 12  layers (total: 88)
(12) Block       : 12  layers (total: 100)
(13) Block       : 12  layers (total: 112)
(14) Block       : 12  layers (total: 124)
(15) Block       : 12  layers (total: 136)
(16) Block       : 12  layers (total: 148)
(17) SeparableConv2d: 2   layers (total: 150)
(18) BatchNorm2d : 1   layers (total: 151)
(19) SeparableConv2d: 2   layers (total: 153)
(20) BatchNorm2d : 1   layers (total: 154)
(21) Linear      : 1   layers (total: 155)


In [12]:
learn = create_cnn(FakeData(), xception_cadene, pretrained=True)

In [13]:
get_groups(nn.Sequential(*learn.model[0], *learn.model[1]), learn.layer_groups)

Group 1: ['Conv2d', 'BatchNorm2d', 'ReLU', 'Conv2d', 'BatchNorm2d', 'Block', 'Block', 'Block', 'Block', 'Block', 'Block']
Group 2: ['Block', 'Block', 'Block', 'Block', 'Block', 'Block', 'SeparableConv2d', 'BatchNorm2d', 'SeparableConv2d', 'BatchNorm2d']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [14]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[-25.6765, -20.7952]])


In [15]:
se_resnet50

NameError: name 'se_resnet50' is not defined

In [16]:
from fastai.vision.models.cadene_models import se_resnet50

In [17]:
arch_summary(se_resnet50)

(0) Sequential  : 4   layers (total: 4)
(1) Sequential  : 38  layers (total: 42)
(2) Sequential  : 50  layers (total: 92)
(3) Sequential  : 74  layers (total: 166)
(4) Sequential  : 38  layers (total: 204)
(5) AvgPool2d   : 1   layers (total: 205)
(6) Linear      : 1   layers (total: 206)


In [18]:
learn = create_cnn(FakeData(), se_resnet50, pretrained=True)

In [19]:
get_groups(nn.Sequential(*learn.model[0], *learn.model[1]), learn.layer_groups)

Group 1: ['Sequential', 'Sequential', 'Sequential']
Group 2: ['Sequential', 'Sequential']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [20]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[-0.5033,  0.0851]])


In [21]:
se_resnet101

NameError: name 'se_resnet101' is not defined

In [22]:
from fastai.vision.models.cadene_models import se_resnet101

In [23]:
arch_summary(se_resnet101)

(0) Sequential  : 4   layers (total: 4)
(1) Sequential  : 38  layers (total: 42)
(2) Sequential  : 50  layers (total: 92)
(3) Sequential  : 278 layers (total: 370)
(4) Sequential  : 38  layers (total: 408)
(5) AvgPool2d   : 1   layers (total: 409)
(6) Linear      : 1   layers (total: 410)


In [24]:
learn = create_cnn(FakeData(), se_resnet101, pretrained=True)

In [25]:
get_groups(nn.Sequential(*learn.model[0], *learn.model[1]), learn.layer_groups)

Group 1: ['Sequential', 'Sequential', 'Sequential']
Group 2: ['Sequential', 'Sequential']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [26]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[-0.3413,  0.4957]])


In [27]:
se_resnext50_32x4d

NameError: name 'se_resnext50_32x4d' is not defined

In [28]:
from fastai.vision.models.cadene_models import se_resnext50_32x4d

In [29]:
arch_summary(se_resnext50_32x4d)

(0) Sequential  : 4   layers (total: 4)
(1) Sequential  : 38  layers (total: 42)
(2) Sequential  : 50  layers (total: 92)
(3) Sequential  : 74  layers (total: 166)
(4) Sequential  : 38  layers (total: 204)
(5) AvgPool2d   : 1   layers (total: 205)
(6) Linear      : 1   layers (total: 206)


In [30]:
learn = create_cnn(FakeData(), se_resnext50_32x4d, pretrained=True)

In [31]:
get_groups(nn.Sequential(*learn.model[0], *learn.model[1]), learn.layer_groups)

Group 1: ['Sequential', 'Sequential', 'Sequential']
Group 2: ['Sequential', 'Sequential']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [32]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[0.5007, 0.1035]])


In [33]:
senet154

NameError: name 'senet154' is not defined

In [34]:
from fastai.vision.models.cadene_models import senet154

In [35]:
arch_summary(senet154)

(0) Sequential  : 10  layers (total: 10)
(1) Sequential  : 38  layers (total: 48)
(2) Sequential  : 98  layers (total: 146)
(3) Sequential  : 434 layers (total: 580)
(4) Sequential  : 38  layers (total: 618)
(5) AvgPool2d   : 1   layers (total: 619)
(6) Dropout     : 1   layers (total: 620)
(7) Linear      : 1   layers (total: 621)


In [36]:
learn = create_cnn(FakeData(), senet154, pretrained=True)

In [37]:
get_groups(nn.Sequential(*learn.model[0], *learn.model[1]), learn.layer_groups)

Group 1: ['Sequential', 'Sequential', 'Sequential']
Group 2: ['Sequential', 'Sequential']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [38]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[1.4733, 0.6690]])


In [39]:
pnasnet5large

NameError: name 'pnasnet5large' is not defined

In [40]:
from fastai.vision.models.cadene_models import pnasnet5large

In [41]:
arch_summary(pnasnet5large)

(0) PNASNet5Large: 839 layers (total: 839)


In [43]:
learn = create_cnn(FakeData(), pnasnet5large, pretrained=True)

In [44]:
get_groups(nn.Sequential(*learn.model[0][0].children(), *learn.model[1]), learn.layer_groups)

Group 1: ['Sequential', 'CellStem0', 'Cell', 'Cell', 'Cell', 'Cell', 'Cell', 'Cell']
Group 2: ['Cell', 'Cell', 'Cell', 'Cell', 'Cell', 'Cell', 'Cell', 'ReLU', 'AvgPool2d', 'Dropout', 'Linear']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']


In [45]:
with torch.no_grad():
    learn.model.eval()
    print(learn.model(torch.randn(1,3,96,96)))

tensor([[0.2652, 0.6582]])


In [14]:
import pretrainedmodels

In [16]:
def inceptionresnetv2(pretrained=False):
    pretrained = 'imagenet' if pretrained else None
    model = pretrainedmodels.inceptionresnetv2(pretrained=pretrained)
    return nn.Sequential(*model.children())

In [17]:
arch_summary(inceptionresnetv2)

(0) BasicConv2d : 3   layers (total: 3)
(1) BasicConv2d : 3   layers (total: 6)
(2) BasicConv2d : 3   layers (total: 9)
(3) MaxPool2d   : 1   layers (total: 10)
(4) BasicConv2d : 3   layers (total: 13)
(5) BasicConv2d : 3   layers (total: 16)
(6) MaxPool2d   : 1   layers (total: 17)
(7) Mixed_5b    : 22  layers (total: 39)
(8) Sequential  : 200 layers (total: 239)
(9) Mixed_6a    : 13  layers (total: 252)
(10) Sequential  : 280 layers (total: 532)
(11) Mixed_7a    : 22  layers (total: 554)
(12) Sequential  : 126 layers (total: 680)
(13) Block8      : 13  layers (total: 693)
(14) BasicConv2d : 3   layers (total: 696)
(15) AvgPool2d   : 1   layers (total: 697)
(16) Linear      : 1   layers (total: 698)


In [18]:
learn = create_cnn(FakeData(), inceptionresnetv2, pretrained=False,
                   cut=-2, split_on=lambda m: (m[0][9], m[1]))

In [19]:
get_groups(nn.Sequential(*learn.model[0], *learn.model[1]), learn.layer_groups)

Group 1: ['BasicConv2d', 'BasicConv2d', 'BasicConv2d', 'MaxPool2d', 'BasicConv2d', 'BasicConv2d', 'MaxPool2d', 'Mixed_5b', 'Sequential']
Group 2: ['Mixed_6a', 'Sequential', 'Mixed_7a', 'Sequential', 'Block8', 'BasicConv2d']
Group 3: ['AdaptiveConcatPool2d', 'Flatten', 'BatchNorm1d', 'Dropout', 'Linear', 'ReLU', 'BatchNorm1d', 'Dropout', 'Linear']
